# Site settings
title: Jerome A. Jackson
email: jacksonjerome@my.fit.edu
description: Mech. Engineer | 3D Modeller | Designer

# Build settings

markdown: kramdown
permalink: pretty

port: 4000

sass:
  sass_dir: assets/css
  style: :nested